#!/usr/bin/env python3
"""Generate the folded-paper origami Z icon as an SVG-in-HTML file.

One paper colour; the 3D read comes from a few LARGE facets, each filled with a
subtle gradient (lit toward the upper-left, darker toward the lower-right) plus
a different base lightness per facet so the folds step. The bold Z is a folded
ribbon: top bar / diagonal / bottom bar, each creased into facets, with small
gusset triangles tucked at the two inner bends. Tunable params up top.
"""

# ---- tunables -------------------------------------------------------------
W = 1024
L, R = 195, 829
T, B = 220, 804
TBAR = 140
DH = 285

HUE, SAT = 256, 30          # single paper hue
GRAD = 6                    # +/- lightness across a facet (the smooth shading)
LMIN, LMAX = 52, 96

# base lightness per facet role (the fold "steps")
LIGHT = {"hi": 88, "mid": 78, "lo": 68, "valley": 60}

# ---- geometry -------------------------------------------------------------
top_y0, top_y1 = T, T + TBAR
bot_y0, bot_y1 = B - TBAR, B
Sl_top, Sr_top = (R - DH, top_y1), (R, top_y1)
Sl_bot, Sr_bot = (L, bot_y0), (L + DH, bot_y0)


def clampL(v):
    return max(LMIN, min(LMAX, v))


def hsl(light):
    return f"hsl({HUE},{SAT}%,{clampL(light):.1f}%)"


def bbox(points):
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return min(xs), min(ys), max(xs), max(ys)


def poly(points):
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


# facet = (points, role).  Folded-ribbon crease layout:
facets = [
    # TOP bar: creased corner-to-corner; upper triangle lit, lower in shade
    ([(L, top_y0), (R, top_y0), (R, top_y1)], "hi"),
    ([(L, top_y0), (R, top_y1), (L, top_y1)], "mid"),
    # DIAGONAL ribbon: split along its length into a lit and a shaded plane
    ([Sr_top, Sl_top, Sl_bot], "mid"),
    ([Sr_top, Sl_bot, Sr_bot], "lo"),
    # BOTTOM bar
    ([(L, bot_y0), (R, bot_y0), (R, bot_y1)], "mid"),
    ([(L, bot_y0), (R, bot_y1), (L, bot_y1)], "lo"),
    # gusset triangles tucked at the two inner bends (deep valley folds)
    ([Sl_top, Sr_top, (R, top_y0)], "valley"),
    ([Sl_bot, Sr_bot, (L, bot_y1)], "valley"),
]

# crease lines (fold edges)
creases = [
    ((L, top_y0), (R, top_y1)),
    (Sr_top, Sl_bot),
    ((L, bot_y0), (R, bot_y1)),
    (Sl_top, Sr_top),
    (Sl_bot, Sr_bot),
]
# ridge highlights (thin bright fold edges)
ridges = [
    ((L, top_y0), (R, top_y0)),
    (Sl_top, Sl_bot),
]

# ---- build svg ------------------------------------------------------------
grad_defs, facet_svg = [], []
for i, (pts, role) in enumerate(facets):
    base = LIGHT[role]
    x0, y0, x1, y1 = bbox(pts)
    grad_defs.append(
        f'<linearGradient id="f{i}" x1="{x0:.0f}" y1="{y0:.0f}" '
        f'x2="{x1:.0f}" y2="{y1:.0f}" gradientUnits="userSpaceOnUse">'
        f'<stop offset="0%" stop-color="{hsl(base + GRAD)}"/>'
        f'<stop offset="100%" stop-color="{hsl(base - GRAD)}"/></linearGradient>')
    facet_svg.append(f'<polygon points="{poly(pts)}" fill="url(#f{i})"/>')

grad_defs = "\n    ".join(grad_defs)
facet_svg = "\n    ".join(facet_svg)
crease_svg = "\n    ".join(
    f'<line x1="{a[0]:.1f}" y1="{a[1]:.1f}" x2="{b[0]:.1f}" y2="{b[1]:.1f}"/>'
    for a, b in creases)
ridge_svg = "\n    ".join(
    f'<line x1="{a[0]:.1f}" y1="{a[1]:.1f}" x2="{b[0]:.1f}" y2="{b[1]:.1f}"/>'
    for a, b in ridges)

Z_SIL = (f"M{L},{top_y0} L{R},{top_y0} L{R},{top_y1} L{Sl_bot[0]},{Sl_bot[1]} "
         f"L{R},{bot_y0} L{R},{bot_y1} L{L},{bot_y1} L{L},{bot_y0} "
         f"L{Sl_top[0]},{Sl_top[1]} L{L},{top_y1} Z")

html = f"""<!DOCTYPE html>
<!-- zahlmeischter app icon — folded-paper origami Z (generated by gen_origami.py) -->
<html>
<head><meta charset="utf-8"><style>html,body{{margin:0;padding:0;background:#262450}}svg{{display:block}}</style></head>
<body>
<svg width="{W}" height="{W}" viewBox="0 0 {W} {W}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="gViolet" cx="20%" cy="18%" r="72%">
      <stop offset="0%" stop-color="#6C5CE7" stop-opacity="0.92"/>
      <stop offset="46%" stop-color="#6C5CE7" stop-opacity="0.46"/>
      <stop offset="100%" stop-color="#6C5CE7" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="gTeal" cx="87%" cy="13%" r="62%">
      <stop offset="0%" stop-color="#4ECDC4" stop-opacity="0.82"/>
      <stop offset="48%" stop-color="#4ECDC4" stop-opacity="0.38"/>
      <stop offset="100%" stop-color="#4ECDC4" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="gPink" cx="12%" cy="90%" r="62%">
      <stop offset="0%" stop-color="#F2A6C8" stop-opacity="0.70"/>
      <stop offset="50%" stop-color="#F2A6C8" stop-opacity="0.32"/>
      <stop offset="100%" stop-color="#F2A6C8" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="gIndigo" cx="90%" cy="92%" r="66%">
      <stop offset="0%" stop-color="#1B1640" stop-opacity="0.95"/>
      <stop offset="55%" stop-color="#1B1640" stop-opacity="0.5"/>
      <stop offset="100%" stop-color="#1B1640" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="vignette" cx="50%" cy="46%" r="76%">
      <stop offset="0%" stop-color="#000000" stop-opacity="0"/>
      <stop offset="66%" stop-color="#000000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000000" stop-opacity="0.34"/>
    </radialGradient>

    {grad_defs}

    <path id="zsil" d="{Z_SIL}"/>
    <clipPath id="clipZ"><use href="#zsil"/></clipPath>

    <filter id="grain" x="0" y="0" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="2" seed="7" result="n"/>
      <feColorMatrix in="n" type="matrix"
        values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.9 0"/>
    </filter>
    <filter id="paperShadow" x="-30%" y="-30%" width="160%" height="160%">
      <feDropShadow dx="0" dy="20" stdDeviation="24" flood-color="#150E2E" flood-opacity="0.5"/>
    </filter>
  </defs>

  <!-- background mesh gradient -->
  <rect width="{W}" height="{W}" fill="#262450"/>
  <rect width="{W}" height="{W}" fill="url(#gViolet)"/>
  <rect width="{W}" height="{W}" fill="url(#gTeal)"/>
  <rect width="{W}" height="{W}" fill="url(#gPink)"/>
  <rect width="{W}" height="{W}" fill="url(#gIndigo)"/>
  <rect width="{W}" height="{W}" fill="url(#vignette)"/>

  <!-- folded paper Z -->
  <g filter="url(#paperShadow)">
    {facet_svg}

    <g stroke="#241B47" stroke-opacity="0.18" stroke-width="1.8" fill="none" stroke-linecap="round">
    {crease_svg}
    </g>
    <g stroke="#ffffff" stroke-opacity="0.35" stroke-width="1.4" fill="none" stroke-linecap="round">
    {ridge_svg}
    </g>

    <g clip-path="url(#clipZ)">
      <rect width="{W}" height="{W}" filter="url(#grain)" opacity="0.05"
            style="mix-blend-mode:multiply"/>
    </g>
    <use href="#zsil" fill="none" stroke="#ffffff" stroke-opacity="0.16" stroke-width="1.5"/>
  </g>
</svg>
</body>
</html>
"""

with open("origami-paper.html", "w") as fh:
    fh.write(html)
print("wrote origami-paper.html  ({} facets)".format(len(facets)))
